[advisories]
yanked = "deny"
ignore = [
  # paste (via aws-lc-rs) is unmaintained
  # https://github.com/aws/aws-lc-rs/issues/722
  "RUSTSEC-2024-0436" 
]

[licenses]
allow = [
    "Apache-2.0",
    "ISC",
    "LicenseRef-webpki",
    "MIT",
]
confidence-threshold = 1.0

# XXX: Figure out how to deal with the Google-source test data
# https://github.com/briansmith/webpki/issues/148.
[[licenses.clarify]]
name = "rustls-webpki"
expression = "LicenseRef-webpki"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]

[bans]
multiple-versions = "deny"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
